### ISSUE TITLE
Formulario de edicion de userAdmin

### ISSUE THREAD

**Issue by paulvazbad** [paulvazbad/ternium#15]
Form para cambiar los valores del usuario

**Comment by AuroTB** [comment]
Estaba pensando que podríamos cambiar un poco el UI a que el usuario pueda hacer modificaciones sin tener que picarle primero al botón de editar. Luego, si edita algo tenga la opción de guardar o no los datos. Entonces, solo tendría un botón para guardar, y si cierra el detalle de usuario los datos modificadon no se guardan.
![image](https://user-images.githubusercontent.com/25405578/56466122-d6870b80-63d1-11e9-8b3c-400228e4cd11.png)

**Comment by paulvazbad** [comment]
Me gusta mucho! Quizas alargar un poco el boton de guardado?

**Comment by paulvazbad** [comment]
# Un  par de observaciones:

- [ ] Agregar otro field para editar el password del usuario en  `EditUserCard`.

- [ ] Al momento de editar algun elemento del formulario que se modifique el estado del componente (this.state.formInfo) con la edicion correspondiente. Que este inicializado con los valores de props.
 
- [ ] Al momento de hacer click al boton de guardado en naranja ejecutarla la siguiente funcion: 
   (this.handleSave)
       `handleSave = () =>{
            this.props.handleSave(this.state.formInfo);
}`

Gracias.

**Comment by AuroTB** [comment]
Hoy hablé con la maestra por zoom y me dijo que tal vez no deberíamos dejar que se pueda modificar el ID.
Y estaba pensando en el porpósito de esta página y creo que se me hace algo muy general, algo que se podría utilizar en cualquier sistema de Ternium donde haya trabajadores.
Entonces, pensaba que podríamos especificarlo más hacia la app que estamos haciendo agregando que puedan igualmente INGRESAR DISPOSITIVOS A LA BASE DE DATOS (mac address y el lugar/area).

**Comment by paulvazbad** [comment]
OK me parece bien lo de dispositivos, estuve hablndo con jorge y creo que llamarle "id" al identificador de cada usuario esalgo confuso. Por lo mismo me parece que la profe penso que estabamos modificando el ID de la base de datos. Ahora el ID de cada usuario se elimino y solamente existe el username.
Por ejemplo el Paul Vazquez mi nuevo username es A00819877 y se borro el field de id.

**Comment by paulvazbad** [comment]
Podriamos poner algo  como los botones de sesiones pasadas con 
_Users_   _devices_
para tener dos listas editables diferentes? o que sugieres para integrar lo de INGRESAR DISPOSITIVOS A LA BASE DE DATOS (mac address y el lugar/area) (No sabia que cada wearable tenia un lugar/area asignada? crei que se podian usar en cualquier zona equipo).
![image](https://user-images.githubusercontent.com/14225515/56687992-23523700-669d-11e9-82ed-be42a21f3aef.png)
