### ISSUE TITLE
¿El supervisor de area deberia poder editar los usuarios de su propia area?

### ISSUE THREAD

**Issue by paulvazbad** [paulvazbad/ternium#22]

**Comment by AuroTB** [comment]
Yo digo que no, no es parte de su trabajo eso.
Tal vez podría enviar un request/comment al SU, pero según yo todo ese movimiento de personal llega desde arriba

**Comment by paulvazbad** [comment]
Ok, entonces no lo implementamos por el momento, te parece si lo preguntamos en el cierre de la tercera etapa?

**Comment by AuroTB** [comment]
claro
