### ISSUE TITLE
En el componente DashboardPage....

### ISSUE THREAD

**Issue by paulvazbad** [paulvazbad/ternium#23]
Es mejor hacer un request al server y que nos regrese toda la lista de sesiones activas y ya nosotros revisar en esa lista cual no esta (se desconecto), para asi nada mas loopear y generar un Dashboard componente por cada sesion en esa lista? Esto tendria las siguientes consecuencias:

- Si se cae una sesion hay que identificarla entre toda la lista y mandarle algun prop para activar el boton de restore sesion y lanzar el toast error.

- Solo se haria un request al backend por lo que si hay muchas sesiones o si un dispositivo tiene latencia baja, se verian afectadas todo el refresh rate del dashboard.

- Seria complicado de administrar que esta desconectado o de hacer retries automaticos de intentar actualizar.

**Comment by AuroTB** [comment]
podemos en todo caso mejor hacer que la lista la tenga backend, y en caso de no recivir ningun dato que nos pongan un número negativo en el primer gas, se me hace más directo porque hardware estan conectados con ellos. Así nos ahorramos la validación de checar toda la lista.
Y según yo el plan siempre es ese, no? de enviar solo un request para que nos mande de un putazo todo. ¿o pensabas solo pedir las visibles? porque recuerda que tenemos que hacer las gráficas.

**Comment by paulvazbad** [comment]
Un solo request gigante y ya nosotros manejamos la lista en un componente` DashboardPage` para renderizar un `gasComponent ` por cada uno.
