### ISSUE TITLE
Poner el logo de Ternium en algun lado

### ISSUE THREAD

**Issue by paulvazbad** [paulvazbad/ternium#3]
No hemos puesto su logo en la app, hay que buca un lugar visible pero no invasivo.

**Comment by AuroTB** [comment]
![image](https://user-images.githubusercontent.com/25405578/55501809-7722b080-5608-11e9-859c-8374d51b89f7.png)

**Comment by AuroTB** [comment]
![image](https://user-images.githubusercontent.com/25405578/55501852-8efa3480-5608-11e9-886f-bab7f946ba1b.png)

**Comment by paulvazbad** [comment]
Me gusta, te parece si nada mas ponemos el cuadrito en la barra de navegacion y el logo completo en otro lado? (Como en la segunda imagen) para conservar el titulo de la app.

**Comment by AuroTB** [comment]
Claro!
