### ISSUE TITLE
Hacer seccion de edicion workers (SA)

### ISSUE THREAD

**Issue by paulvazbad** [paulvazbad/ternium#37]
-Hacer seccion (lista) como userAdmin pero minimizado de nuevo worker y eliminar workers (Aurora).
-POner search bar (opcional) (Paul
-Path Paul
-Requests (Paul)

**Comment by AuroTB** [comment]
![image](https://user-images.githubusercontent.com/25405578/57497253-8a2a3f80-729c-11e9-83fd-35228104c485.png)
