### ISSUE TITLE
Hacer un SVG del icono del device basado en https://material.io/tools/icons/?icon=router&style=baseline

### ISSUE THREAD

**Issue by AuroTB** [paulvazbad/ternium#7]

**Comment by AuroTB** [comment]
![image](https://user-images.githubusercontent.com/25405578/55531130-538e5300-5666-11e9-9a5e-90bcc929f32a.png)

**Comment by AuroTB** [comment]
![image](https://user-images.githubusercontent.com/25405578/55531148-630d9c00-5666-11e9-9dd5-e78d080aae1d.png)

**Comment by paulvazbad** [comment]
Gracias!

**Comment by paulvazbad** [comment]
Se subio como png puedes poner un link al svg mejor?
