### ISSUE TITLE
Hacer el componente SessionCard (La tarjeta con los gases que puso aurora en UXPin

### ISSUE THREAD

**Issue by AuroTB** [paulvazbad/ternium#9]

**Comment by paulvazbad** [comment]
https://material-ui.com/demos/cards/

**Comment by AuroTB** [comment]
Datos prop para tarjeta (ej):
const gasInfo = [
  {
    id: 1,
    name: "Oxígeno",
    lectura: "20.8%"
  },
  {
    id: 2,
    name: "CO",
    lectura: "16 ppm"
  },
  {
    id: 3,
    name: "Explosivo (Hidrógeno)",
    lectura: "0% LEL"
  },
  {
    id: 4,
    name: "Nitrógeno",
    lectura: "4 ppm"
  },
  {
    id: 5,
    name: "H2S",
    lectura: "5 ppm"
  },
  {
    id: 6,
    name: "Gas Natural",
    lectura: "0.6%"
  }
]

export default gasInfo

**Comment by paulvazbad** [comment]
Hey te quedo muy padre la tarjeta!
Una pregunta: cual va a ser el indicador cuando un gas esta fuera de rango? Color rojo al font?

**Comment by AuroTB** [comment]
Lo hice con colores rojo y verde (igual hay uno amarillo por ahí.
¿Qué te parece?
![image](https://user-images.githubusercontent.com/25405578/56175473-fc20a900-5fbc-11e9-9c0c-720c7be7802d.png)

**Comment by AuroTB** [comment]
Aquí estan los límites, no encontre los de los grases de Nitrógeno y Gas Natural:
![image](https://user-images.githubusercontent.com/25405578/56175513-1f4b5880-5fbd-11e9-9437-250b3d4be695.png)
Si se ve muy sutil lo podemos cambiar a otra cosa más notable, como lo que dijiste del color de texto

**Comment by paulvazbad** [comment]
Hola, la verdad si me parece muy sutil y siento que las personas que no ven bien los colores o que estan medio cegatones (como yo) pueden batallar para identificar cuales estan dentro del rango y cuales no :(

**Comment by AuroTB** [comment]
![image](https://user-images.githubusercontent.com/25405578/56249453-76ab0080-6071-11e9-96ed-7466febc3b3f.png)
¿mejor?
